global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'amos'

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dsql'
    scrape_interval: 2s
    static_configs:
      - targets: ['10.60.1.144:9100', '10.60.1.145:9100', '10.60.1.146:9100', '10.60.1.148:9100']

  # - job_name: 'dell'
  #   scrape_interval: 2s
  #   static_configs:
  #     - targets: ['10.61.2.118:9100', '10.61.2.119:9100', '10.61.2.120:9100', '10.61.2.121:9100', '10.61.2.122:9100', '10.61.2.123:9100', '10.61.2.124:9100', '10.61.2.125:9100', '10.61.2.126:9100', '10.61.2.127:9100']

  - job_name: 'hwt'
    scrape_interval: 2s
    static_configs:
      - targets: ['10.61.2.123:9100', '10.61.2.124:9100', '10.61.2.125:9100', '10.61.2.126:9100']
